apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: kuard
  name: kuard
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: kuard
status:
  loadBalancer: {}
