apiVersion: v1
kind: Service
metadata:
  labels:
    app: kuard
  name: kuard-service
spec:
  type: NodePort
  ports:
    - targetPort: 8080
      port: 8080
      nodePort: 30080
      protocol: TCP
  selector:
    name: kuard-service
    app: kuard