#Cria um cluster através do kind, com dois nodes master e três nodes workers
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4  #(versão do kind que rodará nesse cluster)
nodes:
- role: control-plane
- role: control-plane
- role: worker
- role: worker
- role: worker


# Comando para a criação do cluster:
#kind create cluster --name nomeDoCluster --config=arquivo.yaml